CREATE DATABASE IF NOT EXISTS BD_APP_MUSICA;
USE BD_APP_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    RITMO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUN(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    LETRA VARCHAR(350) NOT NULL,
	FK_ARTISTA_CPF VARCHAR(11),
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DURACAO VARCHAR(350) NOT NULL,
	FK_ALBUN_ID INT,
    FK_GENERO_ID INT,
    FOREIGN KEY (FK_ALBUN_ID) REFERENCES ALBUN(ID),
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID)
);