CREATE DATABASE IF NOT EXISTS BD_EST_SUPER;
USE BD_EST_SUPER;

CREATE TABLE IF NOT EXISTS FORECEDOR(
	CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    TIPO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	COD_BARRAS VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(100),
    PRECO DOUBLE,
    FK_CATEGORIA_ID INT,
	FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR_PRODUTO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_FORNECEDOR_CNPJ VARCHAR(14),
    FK_PRODUTO_COD_BARRAS VARCHAR(20),
	FOREIGN KEY (FK_FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ),
    FOREIGN KEY (FK_PRODUTO_COD_BARRAS) REFERENCES PRODUTO(COD_BARRAS)
);